import React, { useEffect, useState, useRef } from "react";
import { useNavigate, useLocation } from "react-router-dom";
import { QRCodeSVG, QRCodeCanvas} from "qrcode.react";
import {FaLinkedin, FaGithub, FaTwitter, FaFacebook, FaInstagram, FaGlobe, FaPhone, FaEnvelope, FaMapMarkerAlt} from "react-icons/fa";
import { jwtDecode } from "jwt-decode";
import axios from "axios";
import "./Portfolio1.css"
const Portfolio1 = ()=>

{
    const qrRef = useRef();

    const downloadQR = () => {
        const canvas = qrRef.current;
        const url = canvas.toDataURL("image/png");

        const link = document.createElement("a");
        link.href = url;
        link.download = "qrcode.png";
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    };

    return (
        <div className="container12">
            <div className="intro12">
                {/* Navbar */}
                <nav className="navbar-port">
                    <h1 className="logo1">
                        Shubhkaran<span className="dot">.</span>
                    </h1>
                    <ul className="nav-links12">
                        <li>Home</li>
                        <li>About</li>
                        <li>
                            <button className="contact-btn12">Contact Me</button>
                        </li>
                    </ul>
                </nav>

                {/* Main Section */}
                <div className="content">
                    {/* Left Section */}
                    <div className="text-section">
                        <div className="hi-section">
                            <h1>
                                Hi! I Am <br/> Shubhkaran Dhillon
                            </h1>
                            <img
                                src="shubh.jpg"
                                alt="William Harry"
                                className="profile-image"
                            />
                        </div>
                        <p>
                            Product designer and digital creative director working in design
                            field for 7 years so far, specialize in user interface design.
                        </p>
                        <div className="buttons">
                            <button className="hire-btn">Hire Me</button>
                            <button className="know-btn" onClick={downloadQR}>Download QR Code</button>
                        </div>
                        <p className="specialization">
                            ⚡ Product Designer and Developer specialized in UI/UX.
                        </p>
                        <div className="socials12"><FaLinkedin/>
                            <FaGithub/>
                            <FaTwitter/>
                            <FaFacebook/></div>
                    </div>

                </div>
            </div>
            <div className="about12">
                <div className="about-left">
                    <QRCodeCanvas ref={qrRef} value={`http://localhost.com`} size={200}/>
                </div>
                <div className="about-right">
                    <h1>About Me</h1>
                    <p>With over a decade of experience in the real estate industry, Jatt has built a reputation as a
                        trusted,
                        results-driven realtor. Specializing in residential and commercial properties, Jatt is committed
                        to providing
                        clients with personalized service and expert guidance throughout every stage of their real
                        estate journey.
                        Whether you're buying your first home, selling a property, or looking for investment
                        opportunities, Jatt's deep knowledge of the local market and attention to detail ensure you make
                        informed decisions. His approach is client-centric, aiming to understand each individual's needs
                        and preferences to deliver tailored solutions that align with their goals. Beyond real estate,
                        Jatt is deeply involved in the community and is always eager to offer support and resources. His
                        passion for helping others and commitment to excellence have earned him repeat business and
                        long-term relationships with clients.
                        Reach out today, and let Jatt help you find your perfect place to call home.(generated by gpt
                        jatt)</p>
                </div>
            </div>
            <div className="contact-container1">
                {/* Left Section (Contact Info) */}
                <div className="contact-info1">
                    <h2>Contact Information</h2>
                    <p>Fill up the form and our team will get back to you within 24 hours.</p>
                    <div className="contact-details1">
                        <p><FaPhone/> +0123 4567 8910</p>
                        <p><FaEnvelope/> hello@flowbase.com</p>
                        <p><FaMapMarkerAlt/> 102 Street 2714 Don</p>
                    </div>
                    <div className="social-icons1">
                        <FaFacebook/>
                        <FaTwitter/>
                        <FaInstagram/>
                        <FaLinkedin/>
                    </div>
                </div>

                {/* Right Section (Form) */}
                <div className="contact-form1">
                    <h2>Contact Us</h2>
                    <form>
                        <div className="form-row1">
                            <input type="text" name="firstName" placeholder="First Name" required/>
                            <input type="text" name="lastName" placeholder="Last Name" required/>
                        </div>
                        <div className="form-row1">
                            <input type="email" name="email" placeholder="Email" required/>
                            <input type="tel" name="phone" placeholder="Phone"/>
                        </div>
                        <div className="form-row1">
                            <input type="text" name="title" placeholder="Title"/>
                            <input type="text" name="company" placeholder="Company"/>
                        </div>
                        <div className="form-group1">
                            <textarea name="notes" placeholder="Notes"></textarea>
                        </div>
                        <div className="form-group1">
                            <button type="submit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
            <div className="footer1">
                <p>Powered By</p>
                <a href="/" target="_blank"><img src="/logo.png"/></a>
            </div>
        </div>
    )
}
export default Portfolio1;